
from enum import Enum, auto


class AccountLogActions(Enum):
    # Communications,
    email_sent = auto(),
    text_sent = auto(),
    # Contributions,
    contribution_added = auto(),
    contribution_updated = auto(),
    contribution_deleted = auto(),
    bulk_contributions_deleted = auto(),
    envelope_created = auto(),
    envelope_updated = auto(),
    envelope_deleted = auto(),
    payment_method_updated = auto(),
    payment_method_deleted = auto(),
    payment_method_created = auto(),
    bank_account_added = auto(),
    bank_account_updated = auto(),
    transfer_day_changed = auto(),
    bank_account_deleted = auto(),
    payment_association_deleted = auto(),
    payment_association_created = auto(),
    bulk_import_contributions = auto(),
    bulk_import_pledges = auto(),
    bulk_pledges_deleted = auto(),
    batch_updated = auto(),
    batch_deleted = auto(),
    bulk_envelopes_deleted = auto(),
    # Events,
    event_created = auto(),
    event_updated = auto(),
    event_deleted = auto(),
    event_instance_deleted = auto(),
    event_future_deleted = auto(),
    events_calendar_created = auto(),
    events_calendar_updated = auto(),
    events_calendar_deleted = auto(),
    bulk_import_attendance = auto(),
    attendance_deleted = auto(),
    bulk_attendance_deleted = auto(),
    # Volunteers,
    volunteer_role_created = auto(),
    volunteer_role_deleted = auto(),
    # People,
    person_created = auto(),
    person_updated = auto(),
    person_deleted = auto(),
    person_archived = auto(),
    person_merged = auto(),
    people_updated = auto(),
    bulk_update_people = auto(),
    bulk_people_deleted = auto(),
    bulk_people_archived = auto(),
    bulk_import_people = auto(),
    bulk_notes_deleted = auto(),
    # Tags,
    tag_created = auto(),
    tag_updated = auto(),
    tag_deleted = auto(),
    bulk_tags_deleted = auto(),
    tag_folder_created = auto(),
    tag_folder_updated = auto(),
    tag_folder_deleted = auto(),
    tag_assign = auto(),
    tag_unassign = auto(),
    # Forms,
    form_created = auto(),
    form_updated = auto(),
    form_deleted = auto(),
    form_entry_updated = auto(),
    form_entry_deleted = auto(),
    # Follow Ups,
    followup_option_created = auto(),
    followup_option_updated = auto(),
    followup_option_deleted = auto(),
    # Users,
    user_created = auto(),
    user_updated = auto(),
    user_deleted = auto(),
    role_created = auto(),
    role_updated = auto(),
    role_deleted = auto(),
    # Extensions,
    extension_installed = auto(),
    extension_uninstalled = auto(),
    extension_upgraded = auto(),
    extension_downgraded = auto(),
    # Account,
    sub_payment_method_updated = auto()
